# ---------------------------
# Individual Host Definitions
# ---------------------------

[testing]
192.168.10.15
testing.domain.com

[appservers]
app01 ansible_host=192.168.1.31 ansible_user=devops ansible_port=2222 ansible_ssh_private_key_file=~/.ssh/app_key
app02 ansible_host=192.168.1.32 ansible_user=devops ansible_port=2222 ansible_ssh_private_key_file=~/.ssh/app_key


[webservers]
web01 ansible_host=192.168.1.11 ansible_fqdn=web01.example.local
web02 ansible_host=192.168.1.12 ansible_fqdn=web02.example.local

[dbservers]
db01 ansible_host=192.168.1.21 ansible_fqdn=db01.example.local
db02 ansible_host=192.168.1.22 ansible_fqdn=db02.example.local

# ---------------------------
# Group-level variables
# ---------------------------

[webservers:vars]
http_port=80
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/id_rsa

[dbservers:vars]
db_port=5432
ansible_user=ansible

# ---------------------------
# Parent group combining children
# ---------------------------

[datacenter:children]
webservers
dbservers

[datacenter:vars]
ansible_python_interpreter=/usr/bin/python3
